spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-recommendations
      database: fitness-recommendations
eureka:
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083